# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  # opnix: sudo opnix token set
  - &doctor age1uxg5gf3ylxlny32kgt3ucgxvy39p87pz3qskp4elydkzqewquveqvtr5gx

  # ssh-to-age: nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  - &prts age1lew4ex3dyrap05gjtk6h3tx94yjvh9kcax69xpfrr6z59q925pdqy047mh
creation_rules:
  - path_regex: secrets/sops-nix.yaml$
    key_groups:
      - age:
          - *doctor
          - *prts
