# Radicale for calendar and contact management
services:
  radicale:
    image: ghcr.io/kozea/radicale:latest
    container_name: radicale
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
    volumes:
      - /tank/radicale/config:/etc/radicale:ro
      - /tank/radicale/data:/var/lib/radicale
    networks:
      - caddy
    labels:
      caddy: radicale.songpola.dev
      caddy.reverse_proxy: "{{upstreams 5232}}"

networks:
  caddy:
    external: true
